#cloud-config
users:
  - default

package_update: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - openjdk-17-jre-headless

write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /etc/systemd/system/minecraft.service
    content: |
      [Unit]
      Description=Minecraft Server
      Documentation=https://www.minecraft.net/en-us/download/server

      [Service]
      WorkingDirectory=/minecraft
      Type=simple
      ExecStart=/usr/bin/java -Xmx2G -Xms2G -jar server.jar nogui
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
runcmd:
  - mkdir -p /minecraft
  - curl -sLSf https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar > /minecraft/server.jar
  - systemctl enable minecraft.service
  - systemctl start minecraft.service
  - sleep 1m
  - echo "eula=true" > /minecraft/eula.txt
  - sed -ir "s/^[#]*\s*max-players=.*/max-players=100/" /minecraft/server.properties
  - sed -ir "s/^[#]*\s*motd=.*/motd=Pulumi Advanced Training/" /minecraft/server.properties
  - sed -ir "s/^[#]*\s*difficulty=.*/difficulty=normal:q/" /minecraft/server.properties
  - sed -ir "s/^[#]*\s*level-seed=.*/level-seed=pulumirocks/" /minecraft/server.properties
  - systemctl restart minecraft.service
  - systemctl enable minecraft.service
